name: HemoCell_CI

on:
# there is no way trigger the workflow when a pull request is merged.
# however, since a merged pull always results in a push, we use the push event here.
  push:
    branches: 
      - master
      - develop
      - setup_cicd
  pull_request:
    types: [opened, reopened, review_requested]
    branches: 
      - develop
      - setup_cicd

jobs:

  hemocell_ci_workflow:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Install hemocell dependencies and create artifacts
      run: |
        sudo apt-get update --yes -qq
        sudo apt-get install --yes -qq git g++ cmake make libopenmpi-dev libhdf5-mpi-dev \
                             libhdf5-dev patch wget ccache
        ./setup.sh > /dev/null
        mkdir -p build && cd build
        export HEMOCELL_BUILD_DIR="$(pwd)"
        cmake .. 
      
    - name : build hemocell and examples
      run : |
        while read target; do
          cmake --build . --target ${target}
        done < <(cut -d '"' -f2 < ../examples/CMakeLists.txt)
      working-directory: build
    
    - name : run validation tests
      run : |
        cmake --build . --target hemocell_test
        export GTEST_FILTER="Validation*"
        ctest -V
      working-directory: build

    -name : build documentation
      run : |
        sudo apt-get update
        sudo apt-get install make doxygen graphviz fonts-freefont-ttf
        pip install -r requirements.txt
        cd user_guide
        make clean
        make html
      working-directory: doc
      
  
