name: HemoCell_CI

on:
  push:
    branches: 
      - develop
      - setup_cicd
  pull_request:
    branches: 
      - develop
      - setup_cicd

jobs:

  before_script:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Install hemocell dependencies and build hemocell
      run: |
        sudo apt-get update --yes -qq
        sudo apt-get install --yes -qq git g++ cmake make libopenmpi-dev libhdf5-mpi-dev libhdf5-dev patch wget ccache
        ./setup.sh > /dev/null
        mkdir -p build && cd build
        cmake ..

  build:

    runs-on: self-hosted

    needs : before_script
    
    steps:
    - uses: actions/checkout@v3
    - name: Build HemoCell examples
      run: |
        while read target; do
          cmake --build . --target ${target}
        done < <(cut -d '"' -f2 < ../examples/CMakeLists.txt)
  
